In [1]:
import numpy as np
print(np.__version__)

2.2.3


In [3]:
list = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(list)
print(arr)
print(type(arr))
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])  
print(arr1)
print(arr1.shape)
print(arr1.size) 
print(arr1[0])
print(arr1[1][2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
[1 2 3]
6


In [7]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,3),5))

print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
arr3 = np.arange(1,13,2)
print(arr3)

[ 1  3  5  7  9 11]


In [10]:
sample = np.array([np.arange(1,10,3),np.arange(2,10,3)])
print(sample)

[[1 4 7]
 [2 5 8]]


In [11]:
arr3 = np.arange(1,13,2)
arr4 = np.arange(2,14,2)
print(arr3+arr4)
print(arr3-arr4)
print(arr3*arr4)
print(arr3**2)


[ 3  7 11 15 19 23]
[-1 -1 -1 -1 -1 -1]
[  2  12  30  56  90 132]
[  1   9  25  49  81 121]


In [15]:
purchase = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120],
    [130,140,150,160]])
total_spend = purchase.sum(axis=1)
average_spend = purchase.mean(axis=1)

print("Total spend: ",total_spend)
print("Average spend: ",average_spend)
print("Max spend: ",max(average_spend))

Total spend:  [100 260 420 580]
Average spend:  [ 25.  65. 105. 145.]
Max spend:  145.0


In [18]:
import numpy as np
A = np.array([[1,2],[4,5]])
B = np.array([9,8,])
solution = np.linalg.solve(A,B)

print(solution)

[-9.66666667  9.33333333]


In [ ]:
sales = np.array([1000,1800,1500,1100,1300,1800,2000,1200,1000,1400])
total_sales = np.sum(sales)
average_sales = sales.mean()
max_sales = max(sales)
min_sales = min(sales)
print("Total sales: ",total_sales)
print("Average sales: ",average_sales)
print("Max sales: ",max_sales)
print("Min sales: ",min_sales)

sales_above_avg = sales[sales>average_sales]
print("Sales above average: ",sales_above_avg)

sales_after_increment = sales*0.1 + sales
print("Sales after increment: ",sales_after_increment)

sorted_sales = np.sort(sales)
print("Sorted sales: ",sorted_sales)

Total sales:  14100
Average sales:  1410.0
Max sales:  2000
Min sales:  1000
Sales above average:  [1800 1500 1800 2000]
Sales after increment:  [1100. 1980. 1650. 1210. 1430. 1980. 2200. 1320. 1100. 1540.]
Sorted sales:  [1000 1000 1100 1200 1300 1400 1500 1800 1800 2000]


In [28]:
import pandas as pd

df = pd.read_csv("sale_data.csv")
df.isnull()

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [29]:
df.fillna(0)

Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           0.0   
1      1002  Mobile Phone  Electronics         1    500           0.0   
2      1003    Headphones  Accessories         3     50           0.0   
3      1004         Mouse  Accessories         2     20           0.0   
4      1005      Keyboard  Accessories         1     30           0.0   
5      1006       T-shirt     Clothing         4     15           0.0   
6      1007        Jacket     Clothing         1     60           0.0   
7      1008  Refrigerator  Electronics         1    900           0.0   
8      1009            TV  Electronics         2   1100           0.0   
9      1010         Shoes     Clothing         2     40           0.0   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10

In [30]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [31]:
df.drop_duplicates()

Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           NaN   
1      1002  Mobile Phone  Electronics         1    500           NaN   
2      1003    Headphones  Accessories         3     50           NaN   
3      1004         Mouse  Accessories         2     20           NaN   
4      1005      Keyboard  Accessories         1     30           NaN   
5      1006       T-shirt     Clothing         4     15           NaN   
6      1007        Jacket     Clothing         1     60           NaN   
7      1008  Refrigerator  Electronics         1    900           NaN   
8      1009            TV  Electronics         2   1100           NaN   
9      1010         Shoes     Clothing         2     40           NaN   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10

In [32]:
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [33]:
pd.to_datetime(df['Date'])

0   2024-02-01
1   2024-02-02
2   2024-02-03
3   2024-02-04
4   2024-02-05
5   2024-02-06
6   2024-02-07
7   2024-02-08
8   2024-02-09
9   2024-02-10
Name: Date, dtype: datetime64[ns]

In [35]:
df['Date'] = pd.to_datetime(df['Date'])
df.dtypes

Order_ID                 int64
Product                 object
Category                object
Quantity                 int64
Price                    int64
Total_Amount           float64
Date            datetime64[ns]
dtype: object

In [39]:
df["Product"] = df.Product.astype('str', errors='ignore')
df.dtypes


Order_ID                 int64
Product                 object
Category                object
Quantity                 int64
Price                    int64
Total_Amount           float64
Date            datetime64[ns]
dtype: object

In [41]:
import numpy as np

data = np.array([10,12,14,15,18,21,25,100])

Q1 = np.percentile(data,25)
Q3 = np.percentile(data,75)
IQR = Q3-Q1

lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR

outliers = data[(data<lower_bound) | (data>upper_bound)]

print("Outliers: ",outliers)


Outliers:  [100]
